apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: basic-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-example 
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: app 
          image: "gcr.io/vault-agent-kubernetes-testing/vault-example-init:0.0.1"
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: "http://10.4.1.22:8200"
